version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: sistem-surat-db
    restart: always
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: sistem_surat
    ports:
      - "5432:5432"
    volumes:
      - postgress-data:/var/lib/postgresql/data
  volumes:
    postgress-data:
      
